### PR TITLE
Add new plot type - differences of O-F

### PR DESCRIPTION
**Pull request by CoryMartin-NOAA**
Add a new plot type that shows O-F for UFO vs O-F for GSI on a scatter plot (and the differences between the two for a map)
Screen Shot 2021-10-14 at 8 45 40 AM

The scatter plot should always be symmetrical about 0 with vmin/vmax for x,y being the same as max(abs(values))

### CODE REVIEW

**Review by RussTreadon-NOAA — COMMENTED** [review]
Changes look good.  Tested on Orion in 2020121500 cycle.   Additional plots (omfdiff.scatter and omfdiff.spatial) are generated and viewable from web interface.   Since I began this review changes were committed to and reverted from feature/plot_omf.   If the work in this branch is done, it's ready to be merged into develop.   If not, I'll review again once final changes are committed.

**Comment by CoryMartin-NOAA** [comment]
Thanks @RussTreadon-NOAA , I am iterating with @aerorahul on different color options for the density scatter plot, trying a new one now and will post once I have a sample.

**Comment by RussTreadon-NOAA** [comment]
@CoryMartin-NOAA  - got it.  I will go ahead and approve this PR since changes will be limited to color options.  You are testing this so once @aerorahul and you are satisfied, please merge into develop.

**Review by RussTreadon-NOAA — APPROVED** [review]
Changes look good.

**Comment by CoryMartin-NOAA** [comment]
I fell down a rabbit hole trying to understand the values of the color bar and found that it seems to be a probability density function for bins which is then interpolated.

Screen Shot 2021-10-14 at 11 48 22 AM

I don't fully understand why there are some negative values as I thought a PDF should be positive. @kevindougherty-noaa is on PTO, and this is calling the density_scatter function in EMCPy, so we may need to open an issue there to figure out exactly what is going on.

**Comment by CoryMartin-NOAA** [comment]
I'm pretty sure that the slight negative values are a function of the interpolation method `'splinef2d'` as if I do nearest-neighbor or linear, I do not see the same negative values. However, it still is not clear to me what this value actually represents. Here: https://numpy.org/doc/stable/reference/generated/numpy.histogram2d.html the documentation says that the uninterpolated values should be:

`bin_count / sample_count / bin_area`
so the 'area', which I assume is a function of variable/channel/etc. (say the area inside each grid box) means that it will be a large area for H(x) and a small area in O-F, resulting in a small PDF for H(x) and a large one for O-F. This obviously won't sum to 1, so like I said, I don't know exactly what is being computed here by numpy's `histogram2d`.

Using this PDF function, I can either: do linear interpolation (won't look as good), normalize the color bar to always be between 0 and 1, or just not plot the color bar. I can also just make the color bar label 'bin_count / sample_count / bin_area' and call it a day.

The other option is to not do a PDF and just return the # of points in each bin, and do a nearest neighbor interpolation to have a color bar of '# of obs'. However, I don't think this will look as _pretty_.

Thoughts/preferences? I'm leaning towards: using the linear interpolation + making the color bar say 'bin_count / sample_count / bin_area' . Changing interpolation method will require a PR in EMCPy.

**Comment by RussTreadon-NOAA** [comment]
Spline interpoloation can (will) overshoot and undershoot.  Linear works around this.   We could try constrained splines.   Linear interpolation is easier to implement.   

Instead of hard wiring the interpolation method in emcpy, function `_density_scatter` could have a third argument specifying the method to use with `interpn`.  This gives the user greater control.  I didn't dig into emcpy to see how easy or hard it is to allow this additional degree of freedom at the user level.    

Is one purpose of the new plots to see how similar or different GSI and UFO PDFs are?   If so, are there other statistical tests we can apply to the two PDFs to generate quantitative measures of "likeness"?  I want to be careful here and not suggest more work than is needed for our evaluation.   

If linear interpolation with a change in the color bar label suffices, no need to complicate things.

**Comment by CoryMartin-NOAA** [comment]
New plots look like so and require the changes in https://github.com/NOAA-EMC/emcpy/pull/74
Screen Shot 2021-10-14 at 4 14 01 PM

**Review by aerorahul — APPROVED** [review]
Looks good.

**Pull request merged**
